{% set name = "xkcdpass" %}
{% set version = "1.19.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xkcdpass-{{ version }}.tar.gz
  sha256: a94f871bda870668e5c65eb84296e939600362df2cc036b91c5ca3815bd292d7

build:
  entry_points:
    - xkcdpass = xkcdpass.xkcd_password:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - xkcdpass
    - xkcdpass.xkcd_password
  commands:
    - pip check
    - xkcdpass --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/redacted/XKCD-password-generator
  summary: Generate secure multiword passwords/passphrases, inspired by XKCD
  license: BSD-3-Clause
  license_file: LICENSE.BSD

extra:
  recipe-maintainers:
    - maffettone
    - mrakitin
