{% set name = "xkcdpass" %}
{% set version = "1.19.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xkcdpass-{{ version }}.tar.gz
  sha256: ceb751e0ab8e442188a114d90de7674fd24357fb1e59045adda3da97c8317531

build:
  entry_points:
    - xkcdpass = xkcdpass.xkcd_password:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - xkcdpass
    - xkcdpass.xkcd_password
  commands:
    - pip check
    - xkcdpass --help
  requires:
    - pip

about:
  home: https://github.com/redacted/XKCD-password-generator
  summary: Generate secure multiword passwords/passphrases, inspired by XKCD
  license: BSD-3-Clause
  license_file: LICENSE.BSD

extra:
  recipe-maintainers:
    - maffettone
    - mrakitin
